"""empty message

Revision ID: 7e2c880580cf
Revises: 
Create Date: 2022-04-12 15:50:33.727890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e2c880580cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.String(length=35), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Food')
    # ### end Alembic commands ###
